"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from .secrets_config import DATABASE, MY_SECRET_KEY

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = MY_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'simple_history',
    'accounts',
    'products',
    'warenhouses',
    'sap_migrations',
    'takings',
    'guardian',
    'mobile',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'crum.CurrentRequestUserMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = DATABASE


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend',
                           'guardian.backends.ObjectPermissionBackend')



# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-ec'

USE_I18N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.sep.join(os.path.abspath(__file__).split(os.sep)[:-2]+['static']),
]

STATIC_URL = 'static/'

MEDIA_ROOT = os.sep.join(os.path.abspath(
    __file__).split(os.sep)[:-2]+['media'])

MEDIA_URL = '/media/'

#loggin config
PATH_LOGS = BASE_DIR / 'logs'
IS_ENABLE_LOGGIN = True
LOGS_FILE_NAME = 'logs.log'
AUTH_USER_MODEL = 'accounts.CustomUserModel'

DEALERS = (
    ('AGENCIAS Y REPRESENTACIONES CORDOVEZ', '1790023516001'),
    ('IMNAC IMPORTADORA NACIONAL', '1791771907001'),
    ('VIDINTERNACIONAL', '1791771907001'),
    ('PROVEEDOR EXTERNO', '9999999999999'),
)

ENTERPRISES_TAKING = (
    ('AGENCIAS Y REPRESENTACIONES CORDOVEZ S.A.','AGENCIAS Y REPRESENTACIONES CORDOVEZ S.A.'),
    ('CORPORACIÓN PLUSBRAND DEL ECUADOR CIA LTDA','CORPORACIÓN PLUSBRAND DEL ECUADOR CIA LTDA'),
    ('IMNAC IMPORTADORA NACIONAL CIA LTDA','IMNAC IMPORTADORA NACIONAL CIA LTDA'),
    ('PANIAGUA S.A.','PANIAGUA S.A.'),
    ('REV ECUADOR S.A','REV ECUADOR S.A'),
    ('SERVMULTIMARC CIA LTDA', 'SERVMULTIMARC CIA LTDA'),
    ('VIDINTERNACIONAL S.A.','VIDINTERNACIONAL S.A.'),
    ('VINOS Y ESPIRITUOSOS DEL LITORAL VINLITORAL S.A.','VINOS Y ESPIRITUOSOS DEL LITORAL VINLITORAL S.A.'),
    ('VINOS Y ESPIRITUOSOS VINESA S.A.','VINOS Y ESPIRITUOSOS VINESA S.A.'),
)

WARENHOUSES_LOCATIONS_NAME = (
    ('VINESA PLAZA NORTE', 'VINESA PLAZA NORTE'),
    ('VINESA CARCELEN', 'VINESA CARCELEN'),
    ('VINLITORAL', 'VINLITORAL'),
    ('SERVMULTIMARC', 'SERVMULTIMARC'),
    ('ALMAGRO QUITO', 'ALMAGRO QUITO'),
)
