name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Update PIP
      run: pip install --upgrade pip
      
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Change Directory
      run: cd src
    - name: Run tests
      run: pytest src/tests/api
